"""ArbiCore — production support + agentic foundation.

Never bypasses the Risk Kernel or LiveModeGuard.
"""

__all__ = [
    "agent_api",
    "agent_loop",
    "alerts",
    "auth",
    "backtest",
    "books",
    "bootstrap",
    "config",
    "critic",
    "domain",
    "drift",
    "features",
    "feed",
    "guards",
    "knowledge",
    "ledger",
    "live_bridge",
    "memory",
    "money",
    "orders",
    "orchestrator",
    "paper_exec",
    "patterns",
    "pipeline",
    "promotion",
    "rebalance",
    "reconcile",
    "reflection",
    "regime",
    "research",
    "risk",
    "safety",
    "scan_hook",
    "scorecard",
    "selection",
    "shadow",
    "signals_agent",
    "similarity",
    "simulator",
    "strategy_registry",
    "streaming",
    "validation",
]
