"""ArbiCore — production support modules for the arbitrage engine.

Agentic foundation (Phases 1–24+) never bypasses the Risk Kernel or LiveModeGuard.
"""

__all__ = [
    "agent_api",
    "agent_loop",
    "alerts",
    "auth",
    "backtest",
    "books",
    "config",
    "critic",
    "domain",
    "features",
    "feed",
    "guards",
    "ledger",
    "memory",
    "money",
    "orders",
    "orchestrator",
    "paper_exec",
    "pipeline",
    "promotion",
    "rebalance",
    "reconcile",
    "reflection",
    "regime",
    "research",
    "risk",
    "safety",
    "selection",
    "shadow",
    "signals_agent",
    "simulator",
    "strategy_registry",
    "streaming",
    "validation",
]
